---
name: Grid-Coord
version: 0.05
author: []
abstract: abstract representation and manipulation of points and rectangles
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.6.1
build_requires:
  Module::Build: 0
  Test::More: 0
provides:
  Grid::Coord:
    file: lib/Grid/Coord.pm
    version: 0.05
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
