--- #YAML:1.0
name: Grid-Coord
version: 0.04
author: ~
abstract: |-
  abstract representation and manipulation of points and rectangles
license: perl
requires:
  perl: 5.6.1
build_requires:
  Module::Build: 0
  Test::More: 0
provides:
  Grid::Coord:
    file: lib/Grid/Coord.pm
    version: 0.04
generated_by: Module::Build version 0.2609
